name: CI

on:
  # every git push (to any branch)
  push:
    branches: ['*']
    # do not run CI for documentation-only changes
    paths-ignore:
      - 'ai/**'
      - 'docs/**'
      - '**/*.md'
  # pull‐request events *against* main, for the "merge-commit" build
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
    # do not run CI for documentation-only changes
    paths-ignore:
      - 'ai/**'
      - 'docs/**'
      - '**/*.md'
env:
  CI: 1
  HUSKY: 0
  PLAYWRIGHT_BROWSERS_PATH: .playwright-browsers
  TURBO_TELEMETRY_DISABLED: 1

jobs:
  lint-build-test:
    runs-on: ubuntu-latest
    steps:
      # checkout project
      - uses: actions/checkout@v4

      # setup tools and install dependencies
      - name: Setup dependencies
        uses: ./.github/actions/setup

      # run CI tasks
      - run: pnpm run lint
      - run: pnpm run build
      - run: pnpm run test
      - run: pnpm run test:e2e

      # upload test reports as artifacts
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: .out/playwright-report/
          retention-days: 30