name: Release

on:
  # watch for CI workflow to finish
  workflow_run:
    branches: [main]
    types:
      - completed
    workflows: ['CI']

concurrency: ${{ github.workflow }}-${{ github.ref }}

env:
  CI: 1
  HUSKY: 0
  TURBO_TELEMETRY_DISABLED: 1

permissions:
  contents: write
  pull-requests: write

jobs:
  publish:
    # only run when CI passed
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      # checkout project
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.COCOBOT_GITHUB_TOKEN }}

      # setup tools and install dependencies
      - name: Setup dependencies
        uses: ./.github/actions/setup

      # perform changesets release operations
      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          commit: 'chore: update versions'
          commitMode: github-api
          title: 'chore: update versions'
          version: pnpm changeset:version
          publish: pnpm changeset:publish
